version: '3.8'

services:
    mysql_db:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: test_user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql_db

volumes:
    mysql-data:
        driver: local
